TrainingArguments:
  num_train_epochs: 1
  warmup_steps: 500
  per_device_train_batch_size: 1
  per_device_eval_batch_size: 1
  weight_decay: 0.01
  evaluation_strategy: "steps"
  logging_steps: 10
  eval_steps: 500
  save_steps: 1e6
  gradient_accumulation_steps: 16