artifacts_root: artifacts

data_extraction:
  root_dir: artifacts/data_extraction
  source: https://github.com/awaistahseen009/datasets/raw/main/samsum_data.zip
  local_data: artifacts/data_extraction/data.zip
  unzip_dir: artifacts/data_extraction

data_validation:
  root_dir: artifacts/data_validation
  status_file: artifacts/data_validation/status.txt
  all_req_files: ['train','test','validation']
  

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_extraction/samsum_dataset
  tokenizer: google/pegasus-cnn_dailymail

model_trainer:
  root_dir: artifacts/model_trainer
  data_path: artifacts/data_extraction/samsum_dataset
  model_ckpt: google/pegasus-cnn_dailymail

model_evaluation:
  root_dir: artifacts/model_evaluation
  data_path: artifacts/data_transformation/samsum_dataset
  model_path: artifacts/model_trainer/pegasus-samsum-model
  tokenizer_path: artifacts/model_trainer/tokenizer
  metric_file_name: artifacts/model_evaluation/metrics.csv